apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 3cx
  description: It is our Meeting Service
  links:
    - url: https://meet.xoho.app/webclient/#/people
      title: 3cx
      icon: web
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/OmerShahzadXoho/devhub/blob/main/3cx.yaml
spec:
  type: Service
  lifecycle: Production
  owner: Xoho Tech
  displayName: omer shahzad

