apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: BitWarden
  description: Use can save you password here it is secure safe of our company 
  links:
    - url: https://safe.xoho.team/#/
      title: Bit Warden
      icon: web
  tags:
    - bitwarden
    - xohotech
    - safe
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/OmerShahzadXoho/devhub/blob/main/BitWarden.yaml
spec:
  type: Service
  lifecycle: Production
  owner: Xoho-Tech
  displayName: Omer_Shahzad
