apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    links:
    - url: https://google.com
      title: My Dashboard
      icon: dashboard
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/OmerShahzadXoho/devhub/blob/main/GitHub.yaml
spec:
  type: Service
  lifecycle: Production
  owner: Xoho Tech
  displayName: Omer_Shahzad
