apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: MatterMost
  description: Communication Tool
  links:
    - url: https://chat.xoho.team/xoho-tech/
      title: Matter Most
      icon: web
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/OmerShahzadXoho/devhub/blob/main/MatterMost.yaml
spec:
  type: Service
  lifecycle: Production
  owner: Xoho Tech
  displayName: Omer_Shahzad
