apiVersion: backstage.io/v1alpha1
services: 
  - 
    name: 3cx
    type: url
    target: "https://meet.xoho.app/webclient/#/people"
  - 
    name: gitlab
    type: url
    target: "https://git.xoho.dev/"
